/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.net.URL;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import services.UserServices;

/**
 *
 * @author ehsas
 */
public class AddAdmin extends javax.swing.JInternalFrame {

    private UserServices userServices;
    boolean myStatus = false;

    public AddAdmin() {
        initComponents();

        userServices = new UserServices();
        this.getContentPane().setBackground(Color.WHITE);

        this.getContentPane().setBackground(Color.WHITE);
        setBorder(BorderFactory.createLineBorder(new Color(201, 201, 201)));
        javax.swing.plaf.InternalFrameUI ifu = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ifu).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtPassword1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        txtConformPass1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddAdmin = new javax.swing.JButton();

        setForeground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(764, 562));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtPassword1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassword1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Name");

        txtName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtName1.setSelectionColor(new java.awt.Color(0, 153, 255));
        txtName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtName1MouseClicked(evt);
            }
        });
        txtName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtName1KeyTyped(evt);
            }
        });

        txtConformPass1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtConformPass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConformPass1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Password");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Conform Pasword");

        btnAddAdmin.setBackground(new java.awt.Color(153, 0, 0));
        btnAddAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAdmin.setText("Add admin");
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });
        btnAddAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnAddAdminKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConformPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConformPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(118, 192, 97, 289);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed

        regAdmin();
        
    }//GEN-LAST:event_btnAddAdminActionPerformed

    public void regAdmin() {
        URL url = getClass().getResource("rolling.gif");
        ImageIcon icon = new ImageIcon(url);
        JLabel lblAnimation = new JLabel(icon);
        JLabel lblWait = new JLabel();
        lblWait.setText("Please wait,Saving admin information ...........");
        lblWait.setFont(new Font("Tahoma", Font.PLAIN, 14));
        lblWait.setForeground(new Color(191, 39, 38));
        JPanel panel1;
        panel1 = new JPanel(new BorderLayout(5, 5));
        panel1.setBackground(Color.WHITE);
        panel1.add(lblWait, BorderLayout.PAGE_START);
        panel1.add(lblAnimation, BorderLayout.CENTER);

        panel1.setBorder(BorderFactory.createEmptyBorder(11, 11, 11, 11));

        final JDialog dialog = new JDialog();
        dialog.getContentPane().add(panel1);
        dialog.setResizable(false);
        dialog.pack();
        dialog.setSize(500, 180);
        dialog.setLocationRelativeTo(null);
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.setAlwaysOnTop(false);
        dialog.setVisible(true);

        SwingWorker worker = new SwingWorker() {

            @Override
            protected void done() {
                // Close the dialog
                dialog.dispose();
            }

            @Override
            protected void process(List chunks) {

            }

            @Override
            protected Object doInBackground() throws Exception {

                String name = txtName1.getText();
                String password = new String(txtPassword1.getPassword());
                String conformPass = new String(txtConformPass1.getPassword());
//                String password = txtPassword.getText();
//                String conformPass = txtConformPass.getText();

                if (name.equals("") || name.equals("Name") || password.equals("") || password.equals("Password") || conformPass.equals("") || conformPass.equals("Conform Password")) {

                    JOptionPane.showMessageDialog(txtName1, "Please enter admin information");
                } else if (!(password.equals(conformPass))) {
                    JOptionPane.showMessageDialog(txtName1, "Conform password not same");
                } else {

                    boolean status = userServices.addAdminInfo(name, password, conformPass);

                    if (status == true) {
                        JOptionPane.showMessageDialog(txtName1, "Admin information added sucessfully");

                        txtConformPass1.setText("");
                        txtName1.setText("");
                        txtPassword1.setText("");
                    } else {
                        JOptionPane.showMessageDialog(txtName1, "Admin information not added");
                    }

                }
                return null;
            }
        };

        worker.execute();

    }
    private void txtName1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtName1MouseClicked
        txtName1.setText("");
        txtName1.setForeground(Color.BLACK);

    }//GEN-LAST:event_txtName1MouseClicked

    private void txtPassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassword1MouseClicked
        txtPassword1.setText("");
        txtPassword1.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPassword1MouseClicked

    private void txtConformPass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConformPass1MouseClicked
        txtConformPass1.setText("");
        txtConformPass1.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtConformPass1MouseClicked

    private void txtName1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName1KeyTyped
       
    }//GEN-LAST:event_txtName1KeyTyped

    private void btnAddAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddAdminKeyTyped
        regAdmin();
    }//GEN-LAST:event_btnAddAdminKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtConformPass1;
    private javax.swing.JTextField txtName1;
    private javax.swing.JPasswordField txtPassword1;
    // End of variables declaration//GEN-END:variables
}
